# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rampart < Formula
  desc "Open-source firewall for AI agents"
  homepage "https://rampart.sh"
  version "0.2.27"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peg/rampart/releases/download/v0.2.27/rampart_0.2.27_darwin_amd64.tar.gz"
      sha256 "8563fc4e11597a8b20d361b29bd3e204faf13aacd746a96c279aaa310b319e78"

      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peg/rampart/releases/download/v0.2.27/rampart_0.2.27_darwin_arm64.tar.gz"
      sha256 "0c0f1e4778065ac29c6457ff73ef78961cdf4524d1628cf6ea14ddb98378df8e"

      def install
        bin.install "rampart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.2.27/rampart_0.2.27_linux_amd64.tar.gz"
      sha256 "b6279456c1fe770af11a5d98ed73447603d6850d67e75efb08e55c16baef67d6"
      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.2.27/rampart_0.2.27_linux_arm64.tar.gz"
      sha256 "eb19f61147780ce245b46bda1a454d1b3030380064d1758ee6046f50cf0fd618"
      def install
        bin.install "rampart"
      end
    end
  end

  test do
    system "#{bin}/rampart", "version"
  end
end
