# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rampart < Formula
  desc "Open-source firewall for AI agents"
  homepage "https://rampart.sh"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peg/rampart/releases/download/v0.2.3/rampart_0.2.3_darwin_amd64.tar.gz"
      sha256 "d0c5328cf2e9fb54fc72ae817e1cdf665a6cb2b866fb684f05fa478cee6320bd"

      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peg/rampart/releases/download/v0.2.3/rampart_0.2.3_darwin_arm64.tar.gz"
      sha256 "3c7cbad4c5311845edc67267ff2adf562c71196f5807c02054e19bc90c879fb0"

      def install
        bin.install "rampart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.2.3/rampart_0.2.3_linux_amd64.tar.gz"
      sha256 "262be5eadf0b0a49682d69039172e391e9d4367181ed28e1ed12ecd334339831"
      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.2.3/rampart_0.2.3_linux_arm64.tar.gz"
      sha256 "90ecfdf8a08a232d55df0957e4399b15d3393b51615aafed67db2d82bc2bfcc7"
      def install
        bin.install "rampart"
      end
    end
  end

  test do
    system "#{bin}/rampart", "version"
  end
end
