# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rampart < Formula
  desc "Open-source firewall for AI agents"
  homepage "https://rampart.sh"
  version "0.2.31"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peg/rampart/releases/download/v0.2.31/rampart_0.2.31_darwin_amd64.tar.gz"
      sha256 "a1e9f724dd652c134d1d582d48b6e90e0face5cfd6bc1c6938e8ad6ee23c07f1"

      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peg/rampart/releases/download/v0.2.31/rampart_0.2.31_darwin_arm64.tar.gz"
      sha256 "9ac5746d7d2af9998d62f70ce71cbe15d4100d4a658b4ead6d23272b800e499f"

      def install
        bin.install "rampart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.2.31/rampart_0.2.31_linux_amd64.tar.gz"
      sha256 "6e8bf3811339cf13569cade87669bdb31bdb30f0ee74ee8cee13036194c83015"
      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.2.31/rampart_0.2.31_linux_arm64.tar.gz"
      sha256 "923dc96269bf21e685225ae959aec9e0c3a467b7ac40dc82c3a82bc7d5f4200c"
      def install
        bin.install "rampart"
      end
    end
  end

  test do
    system "#{bin}/rampart", "version"
  end
end
