# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rampart < Formula
  desc "Open-source firewall for AI agents"
  homepage "https://rampart.sh"
  version "0.6.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peg/rampart/releases/download/v0.6.9/rampart_0.6.9_darwin_amd64.tar.gz"
      sha256 "3d89be1274331c870a40fb56f49a5b0fd265afb0b94f047e62239ddff806bbf3"

      define_method(:install) do
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peg/rampart/releases/download/v0.6.9/rampart_0.6.9_darwin_arm64.tar.gz"
      sha256 "e4b474fc91afbca00f3f418aa0c31b4e9e577ed77e2e236a2bb659f9137a95cb"

      define_method(:install) do
        bin.install "rampart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.6.9/rampart_0.6.9_linux_amd64.tar.gz"
      sha256 "5a18f557980a5b230bc02e40dacd4dfc4f6f9b86adb27b907f5acc4a357e0978"
      define_method(:install) do
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.6.9/rampart_0.6.9_linux_arm64.tar.gz"
      sha256 "2dc26299be6220cda0293b641b59e3045df484645e9d59a05313e273ff819f29"
      define_method(:install) do
        bin.install "rampart"
      end
    end
  end

  test do
    system "#{bin}/rampart", "version"
  end
end
