# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rampart < Formula
  desc "Open-source firewall for AI agents"
  homepage "https://rampart.sh"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peg/rampart/releases/download/v0.3.1/rampart_0.3.1_darwin_amd64.tar.gz"
      sha256 "53500fde83b3b2dc1e36d35587f18f6e0d520be1331b676e7fc0c059c186ab4a"

      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peg/rampart/releases/download/v0.3.1/rampart_0.3.1_darwin_arm64.tar.gz"
      sha256 "879ed53a839e321224c88d64cd2707816491974f916097d9c28e635aa1668b6a"

      def install
        bin.install "rampart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.3.1/rampart_0.3.1_linux_amd64.tar.gz"
      sha256 "3a18bd247ddad2f9cd1732a517c7b0820ed4d41798dbe0613d569e3ff2fbe639"
      def install
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peg/rampart/releases/download/v0.3.1/rampart_0.3.1_linux_arm64.tar.gz"
      sha256 "8ca16b31c2bb2c9b9fe7a40e4eb74da4ed86844713de2eb251fcd138dd83ce6c"
      def install
        bin.install "rampart"
      end
    end
  end

  test do
    system "#{bin}/rampart", "version"
  end
end
